version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    environment:
     - TZ=America/Buenos_Aires
     - PHP_ENABLE_XDEBUG=1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8155:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - red
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    #volumes:
    #  - ~/mysql:/var/lib/mysql
    networks:
     - red
 
networks:
  red:
    driver: bridge
    ipam:
      config:
      - subnet: "${SUBNET_DOCKER_NETWORK}"
      
volumes:
  my-db: